version: '3.8'
services:
    coffeeshopdb:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Test@1234"
            MSSQL_PID: Express
        ports:
            - "1433:1433"
    coffeeshop-backend:
        image: thatz98/coffeeshop-backend:latest
        depends_on:
            - coffeeshopdb
        environment:
            ServerName: "coffeeshopdb"
            Database: "Employee"
            UserName: "SA"
            Password: "Test@1234"
        ports:
            - "1337:80"
    coffeeshopfrontend:
        image: thatz98/coffeeshop-frontend:latest
        ports:
            - "3003:80"
