// <auto-generated />
using Employee.DataAccessLayer.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Employee.API.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    partial class EmployeeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Employee.DataAccessLayer.Coffee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Coffees");

                    b.HasData(
                        new
                        {
                            Id = "e7c06fb2-f188-4927-af2c-acb734e9781b",
                            Description = "A strong, concentrated coffee beverage made by forcing pressurized hot water through finely ground coffee beans.",
                            Name = "Espresso",
                            Price = 300.0,
                            Rating = 4
                        },
                        new
                        {
                            Id = "a5ef22d6-ed6c-4989-9068-b0239cedcc6f",
                            Description = " A coffee beverage made with espresso and steamed milk, topped with a small amount of foam. ",
                            Name = "Latte",
                            Price = 550.0,
                            Rating = 5
                        },
                        new
                        {
                            Id = "d75541d1-1ba0-47ef-afdc-5273c7f8ea27",
                            Description = "A coffee drink made with equal parts espresso, steamed milk and milk foam.",
                            Name = "Cappuccino",
                            Price = 450.0,
                            Rating = 3
                        });
                });

            modelBuilder.Entity("Employee.DataAccessLayer.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = "84981468-0753-48e7-ae92-47c1bdbdc0a1",
                            Age = 50,
                            FirstName = "David",
                            LastName = "Mike"
                        },
                        new
                        {
                            Id = "eb3f6b85-4e99-4347-8d18-67c047adba30",
                            Age = 50,
                            FirstName = "Steve",
                            LastName = "Warner"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
